### ISSUE TITLE
Symfony 1. Several applications in a project.

### ISSUE THREAD

**Issue by ruslan-polutsygan** [theodo/TheodoEvolutionLegacyWrapperBundle#19]
Hi @benja-M-1 

I'm trying to wrap legacy symfony1 project using the bundle.

It is pretty common situation when there are two applications(in terms of symfony1) in single project - one for frontend and another for backend.

However, currently it's not poosible to run more than one symfony1 application. Application name must be defined via bundle parameters. 

What do you think, wouldn't it be a better to dispatch an event there https://github.com/theodo/TheodoEvolutionLegacyWrapperBundle/blob/master/Kernel/Symfony14Kernel.php#L47 to provide ability to update application name and/or other params depending on request?
I can work on PR if you are OK with such solution.

Thanks

**Comment by benja-M-1** [comment]
Yes that's a good idea!

**Comment by jacobkiers** [comment]
I think this can be closed.

**Comment by ruslan-polutsygan** [comment]
yep :)
