### ISSUE TITLE
Problem with Unit Testing CodeIgniter legacy

### ISSUE THREAD

**Issue by tsantos84** [theodo/TheodoEvolutionLegacyWrapperBundle#25]
I'm facing a problem when I do a smoke test like bellow: 

```php
    /**
     * @dataProvider getLegacyRoutes
     */
    public function testIndex($uri)
    {
        $client = static::createClient();
        $client->request('GET', $uri);
        $this->assertEquals(200, $client->getResponse()->getStatusCode());
    }

    public function getLegacyRoutes()
    {
        return [
            ['/route_1'],
            ['/route_2']
        ];
    }
```

The first route is tested properly but the second one throws the exception message:

    Constant ENVIRONMENT already defined

It seems to me that the kernel is booting for each request made by the client.

**Comment by tsantos84** [comment]
I did two little changes in my local copy and now the unit tests work like a charm. What is the best way to contribute? Put the changes here or fork the code and make a pull request to you?

**Comment by benja-M-1** [comment]
Hi @tsantos84 glad you found a solution. The best way to share your fix is to fork and submit a PR :) Thank you
