### ISSUE TITLE
onKernelFinishRequest raises an FATAL ERROR when using Symfony 2.3 standard edition

### ISSUE THREAD

**Issue by thierrymarianne** [theodo/TheodoEvolutionLegacyWrapperBundle#8]
PHP Fatal error:  Undefined class constant 'FINISH_REQUEST'

This constant was introduced with Symfony2.4 

http://api.symfony.com/2.3/Symfony/Component/HttpKernel/KernelEvents.html
http://api.symfony.com/2.4/Symfony/Component/HttpKernel/KernelEvents.html

Shouldn't we let the user declare this method when needed?

**Comment by stof** [comment]
@thierrymarianne this is not an issue. Typehints don't trigger the autoloading, and use statements either. It is perfectly possible to reference a class which does not exists (this is how optional deps are working)

**Comment by thierrymarianne** [comment]
@stof well noted, thanks.

**Comment by stof** [comment]
This should not be closed. The ``getSubscribedEvents`` method still need to be adapter to check for undefined constants (similar to what https://github.com/symfony/SwiftmailerBundle/blob/master/EventListener/EmailSenderListener.php#L74 does except it should check for the constant to exist, not for a class)

**Comment by thierrymarianne** [comment]
@stof Sorry for having misunderstood your comment. I'll check the SwiftMailer example in order to offer some resolution.

**Comment by benja-M-1** [comment]
@thierrymarianne  I'll do the PR, that's exactly what I told you :)

**Comment by thierrymarianne** [comment]
Great! Thank you, @benja-M-1!
